name: spustit skript

on:
  schedule:
    - cron: "0 4 * * *"   # spustí se každý den v 4:00 ráno UTC
  workflow_dispatch:       # umožní spustit i ručně v GitHubu

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python rozvrh.py
